### ISSUE TITLE
База данных

### ISSUE THREAD

**Issue by crysan** [Krakozaber/EGRUL-EGRIP#1]
Добрый!
Подскажите, а нет у Вас случайно базы данных ЕГРЮЛ и ЕГРИП.
Мне нужна не сама база, а только ее структура таблиц.
Если есть и Вам было бы не сложно с ней поделиться, то прошу Вас помочь мне в данном вопросе.
Спасибо!

**Comment by Krakozaber** [comment]
Добрый!
Есть модельки и разбор написанный на php (Yii2), но без миграций и без БД.

**Comment by crysan** [comment]
Спасибо!
Но вопрос уже решен.
Доброго дня!
